// const baseUrl="http://172.17.228.131:3000";//172.17.235.30:8080
// const baseUrl="http://172.17.235.30:8080";
//const baseUrl="https://echo-gfas.herokuapp.com";
const baseUrl1="http://172.17.235.30:8080";
const baseUrl="https://echo-cbt-server.herokuapp.com";

const url_getAllPosts="$baseUrl/auth/allPosts";
const url_uploadPost="$baseUrl/auth/uploadPost";
const url_register="$baseUrl/create_user";
const url_login="$baseUrl/user/get";
const url_startChat="$baseUrl/auth/startchat";
const url_getAllChats="$baseUrl/auth/getChats";
const url_getAllMessages="$baseUrl/auth/getAllMessages";
const url_getAllActivities="$baseUrl1/getSuggestions";
const url_getArticles="$baseUrl1/getArticles";
const url_getBaseArticles="$baseUrl/getArticles";
const url_sendDailyActivites="$baseUrl/user/activity/submit";
const url_getDailyActivites="$baseUrl/user/activity/daily";
const url_sendTherapistEmail="$baseUrl/user/guide/email";
const url_recordDiary="$baseUrl/user/addDiary";
const url_getDiaryEntries="$baseUrl/user/getDiary";
const url_getAllArticles ="$baseUrl/user/suggestion/articles";
